stages:
  - build

image: docker.antmicro.com:5000/repositories/basic-docker-images/debian-vivado:v2019.2

before_script:
  - apt -qy update
  - apt -qy install git build-essential python3 python3-pip python3-wheel gcc-riscv64-linux-gnu
  - git config --global credential.helper 'cache --timeout=2400'
  - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@dev.antmicro.com/git/litex-rowhammer-tester.git # just to cache the token
  - git submodule update --init --recursive
  - pip3 install -r requirements.txt
  - export PATH=$PATH:$(echo $PWD/riscv64-*/bin/):/opt/Xilinx/Vivado/2019.2/bin

etherbone_bitstream:
  stage: build
  script:
    - python3 third_party/litex-boards/litex_boards/targets/lpddr4_test_board.py --with-etherbone --build
    - mkdir etherbone_artifacts
    - cp build/lpddr4_test_board/gateware/*.bit etherbone_artifacts/
    - cp build/lpddr4_test_board/gateware/*.rpt etherbone_artifacts/
  artifacts:
    paths:
      - etherbone_artifacts

hyperram_bitstream:
  stage: build
  script:
    - python3 third_party/litex-boards/litex_boards/targets/lpddr4_test_board.py --with-hyperram --build
    - mkdir hyperram_artifacts
    - cp build/lpddr4_test_board/gateware/*.bit hyperram_artifacts/
    - cp build/lpddr4_test_board/gateware/*.rpt hyperram_artifacts/
  artifacts:
    paths:
      - hyperram_artifacts

sdcard_bitstream:
  stage: build
  script:
    - python3 third_party/litex-boards/litex_boards/targets/lpddr4_test_board.py --with-etherbone --with-sdcard --build
    - mkdir sdcard_artifacts
    - cp build/lpddr4_test_board/gateware/*.bit sdcard_artifacts/
    - cp build/lpddr4_test_board/gateware/*.rpt sdcard_artifacts/
  artifacts:
    paths:
      - sdcard_artifacts

dram_bitstream:
  stage: build
  script:
    - python3 third_party/litex-boards/litex_boards/targets/lpddr4_test_board.py --with-uartbone --rw-bios-mem --csr-csv csr.csv --with-sdram --build
    - mkdir dram_artifacts
    - cp build/lpddr4_test_board/gateware/*.bit dram_artifacts/
    - cp build/lpddr4_test_board/gateware/*.rpt dram_artifacts/
    - cp csr.csv dram_artifacts/
  artifacts:
    paths:
      - dram_artifacts
